import { UserRole } from "@/dto/constants/UserRole";
import { RiskLevel } from "@/dto/constants/RiskLevel";
import type { User } from "@/dto/auth/User";
import type { Patient } from "@/dto/patient/Patient";
import type { HospitalVisit } from "@/dto/visit/HospitalVisit";
import type { TestOrder } from "@/dto/diagnostics/TestOrder";
import type { Prescription } from "@/dto/prescription/Prescription";
import type { Medicine } from "@/dto/medicine/Medicine";
import type { MedicineTransaction } from "@/dto/medicine/MedicineTransaction";
import type { Bill } from "@/dto/billing/Bill";
import type { AuditLog } from "@/dto/audit/AuditLog";
import type { Facility } from "@/dto/facility/Facility";

export interface DemoAccount {
  username: string;
  role: UserRole;
  user: User;
  description: string;
}

export const demoAccounts: DemoAccount[] = [
  // 5 Patients
  {
    username: "patient01",
    role: UserRole.PATIENT,
    description: "Meera Sharma · 58y (Hypertension / Diabetes)",
    user: { id: "p-01", name: "Meera Sharma", role: UserRole.PATIENT, facilityId: "phc-1" },
  },
  {
    username: "patient02",
    role: UserRole.PATIENT,
    description: "Ramesh Patel · 45y (Cardiology follow-up)",
    user: { id: "p-02", name: "Ramesh Patel", role: UserRole.PATIENT, facilityId: "phc-1" },
  },
  {
    username: "patient03",
    role: UserRole.PATIENT,
    description: "Sunita Devi · 34y (Maternal health & vitals)",
    user: { id: "p-03", name: "Sunita Devi", role: UserRole.PATIENT, facilityId: "chc-1" },
  },
  {
    username: "patient04",
    role: UserRole.PATIENT,
    description: "Arjun Singh · 62y (High-risk Respiratory care)",
    user: { id: "p-04", name: "Arjun Singh", role: UserRole.PATIENT, facilityId: "phc-2" },
  },
  {
    username: "patient05",
    role: UserRole.PATIENT,
    description: "Kavita Joshi · 28y (Routine checkup & vaccinations)",
    user: { id: "p-05", name: "Kavita Joshi", role: UserRole.PATIENT, facilityId: "sub-1" },
  },

  // 5 Healthcare Workers
  {
    username: "healthcare01",
    role: UserRole.HEALTHCARE_WORKER,
    description: "Sunita Verma · ASHA Facilitator (Rampur PHC)",
    user: { id: "hw-01", name: "Sunita Verma (ASHA)", role: UserRole.HEALTHCARE_WORKER, facilityId: "phc-1" },
  },
  {
    username: "healthcare02",
    role: UserRole.HEALTHCARE_WORKER,
    description: "Rekha Yadav · ANM Nurse (Kosi CHC)",
    user: { id: "hw-02", name: "Rekha Yadav (ANM)", role: UserRole.HEALTHCARE_WORKER, facilityId: "chc-1" },
  },
  {
    username: "healthcare03",
    role: UserRole.HEALTHCARE_WORKER,
    description: "Pooja Sharma · CHO Officer (Sitapur PHC)",
    user: { id: "hw-03", name: "Pooja Sharma (CHO)", role: UserRole.HEALTHCARE_WORKER, facilityId: "phc-2" },
  },
  {
    username: "healthcare04",
    role: UserRole.HEALTHCARE_WORKER,
    description: "Manish Kumar · Field Health Worker (Rampur)",
    user: { id: "hw-04", name: "Manish Kumar", role: UserRole.HEALTHCARE_WORKER, facilityId: "phc-1" },
  },
  {
    username: "healthcare05",
    role: UserRole.HEALTHCARE_WORKER,
    description: "Geeta Devi · Mobile Health Unit Lead (Kosi)",
    user: { id: "hw-05", name: "Geeta Devi", role: UserRole.HEALTHCARE_WORKER, facilityId: "dh-1" },
  },

  // 5 Hospital Staff (Reception, Check-in, OPD)
  {
    username: "hospitalstaff01",
    role: UserRole.HOSPITAL_STAFF,
    description: "Rajesh Tiwari · OPD Reception Desk (Rampur PHC)",
    user: { id: "hs-01", name: "Rajesh Tiwari (OPD Reception)", role: UserRole.HOSPITAL_STAFF, facilityId: "phc-1" },
  },
  {
    username: "hospitalstaff02",
    role: UserRole.HOSPITAL_STAFF,
    description: "Amit Choudhary · Central Admission (District Hosp)",
    user: { id: "hs-02", name: "Amit Choudhary (Admissions)", role: UserRole.HOSPITAL_STAFF, facilityId: "dh-1" },
  },
  {
    username: "hospitalstaff03",
    role: UserRole.HOSPITAL_STAFF,
    description: "Kiran Bala · Triage Token Desk (Kosi CHC)",
    user: { id: "hs-03", name: "Kiran Bala (Token Desk)", role: UserRole.HOSPITAL_STAFF, facilityId: "chc-1" },
  },
  {
    username: "hospitalstaff04",
    role: UserRole.HOSPITAL_STAFF,
    description: "Vikas Sharma · OPD Operations Desk (Rampur PHC)",
    user: { id: "hs-04", name: "Vikas Sharma (Ops Desk)", role: UserRole.HOSPITAL_STAFF, facilityId: "phc-1" },
  },
  {
    username: "hospitalstaff05",
    role: UserRole.HOSPITAL_STAFF,
    description: "Deepak Rawat · Patient Navigator (District Hosp)",
    user: { id: "hs-05", name: "Deepak Rawat (Helpdesk)", role: UserRole.HOSPITAL_STAFF, facilityId: "dh-1" },
  },

  // 5 Hospital Admins
  {
    username: "hospitaladmin01",
    role: UserRole.ADMIN,
    description: "Aditya Malhotra · Medical Superintendent (Rampur PHC)",
    user: { id: "ha-01", name: "Aditya Malhotra (Superintendent)", role: UserRole.ADMIN, facilityId: "phc-1" },
  },
  {
    username: "hospitaladmin02",
    role: UserRole.ADMIN,
    description: "Dr. Vandana Rao · CMO (District Hospital Kosi)",
    user: { id: "ha-02", name: "Dr. Vandana Rao (CMO)", role: UserRole.ADMIN, facilityId: "dh-1" },
  },
  {
    username: "hospitaladmin03",
    role: UserRole.ADMIN,
    description: "Suresh Chandra · Facility Ops Manager (Kosi CHC)",
    user: { id: "ha-03", name: "Suresh Chandra (Facility Ops)", role: UserRole.ADMIN, facilityId: "chc-1" },
  },
  {
    username: "hospitaladmin04",
    role: UserRole.ADMIN,
    description: "Meenakshi Iyer · Quality & Audit Director",
    user: { id: "ha-04", name: "Meenakshi Iyer (Audit Dir)", role: UserRole.ADMIN, facilityId: "dh-1" },
  },
  {
    username: "hospitaladmin05",
    role: UserRole.ADMIN,
    description: "Naveen Gupta · Health Administration (Sitapur PHC)",
    user: { id: "ha-05", name: "Naveen Gupta (Admin)", role: UserRole.ADMIN, facilityId: "phc-2" },
  },

  // 5 Doctors
  {
    username: "doctor01",
    role: UserRole.DOCTOR,
    description: "Dr. Anita Rao · Senior Physician (General Medicine)",
    user: { id: "doc-01", name: "Dr. Anita Rao", role: UserRole.DOCTOR, facilityId: "phc-1" },
  },
  {
    username: "doctor02",
    role: UserRole.DOCTOR,
    description: "Dr. Rajesh Kumar · Cardiologist (District Hosp)",
    user: { id: "doc-02", name: "Dr. Rajesh Kumar", role: UserRole.DOCTOR, facilityId: "dh-1" },
  },
  {
    username: "doctor03",
    role: UserRole.DOCTOR,
    description: "Dr. Priya Singh · Pediatrician (Kosi CHC)",
    user: { id: "doc-03", name: "Dr. Priya Singh", role: UserRole.DOCTOR, facilityId: "chc-1" },
  },
  {
    username: "doctor04",
    role: UserRole.DOCTOR,
    description: "Dr. Suresh Verma · Orthopedic Surgeon (District Hosp)",
    user: { id: "doc-04", name: "Dr. Suresh Verma", role: UserRole.DOCTOR, facilityId: "dh-1" },
  },
  {
    username: "doctor05",
    role: UserRole.DOCTOR,
    description: "Dr. Meenakshi Sundaram · Gynecologist (Rampur PHC)",
    user: { id: "doc-05", name: "Dr. Meenakshi Sundaram", role: UserRole.DOCTOR, facilityId: "phc-1" },
  },

  // 5 Pharmacy Staff
  {
    username: "pharmacy01",
    role: UserRole.PHARMACY,
    description: "Ravi Shastri · Chief Pharmacist (Rampur PHC)",
    user: { id: "ph-01", name: "Ravi Shastri (Pharmacist)", role: UserRole.PHARMACY, facilityId: "phc-1" },
  },
  {
    username: "pharmacy02",
    role: UserRole.PHARMACY,
    description: "Neha Aggarwal · Dispensing Pharmacist (District Hosp)",
    user: { id: "ph-02", name: "Neha Aggarwal (Pharmacist)", role: UserRole.PHARMACY, facilityId: "dh-1" },
  },
  {
    username: "pharmacy03",
    role: UserRole.PHARMACY,
    description: "Sunil Pal · Pharmacy Tech (Kosi CHC)",
    user: { id: "ph-03", name: "Sunil Pal", role: UserRole.PHARMACY, facilityId: "chc-1" },
  },
  {
    username: "pharmacy04",
    role: UserRole.PHARMACY,
    description: "Praveen Joshi · Stock & Inventory Lead",
    user: { id: "ph-04", name: "Praveen Joshi", role: UserRole.PHARMACY, facilityId: "phc-1" },
  },
  {
    username: "pharmacy05",
    role: UserRole.PHARMACY,
    description: "Anjali Saxena · Emergency Drug Counter (District Hosp)",
    user: { id: "ph-05", name: "Anjali Saxena", role: UserRole.PHARMACY, facilityId: "dh-1" },
  },

  // 5 Lab Staff
  {
    username: "lab01",
    role: UserRole.LAB,
    description: "Dinesh Kumar · Chief Lab Tech (Rampur PHC)",
    user: { id: "lb-01", name: "Dinesh Kumar (Lab Tech)", role: UserRole.LAB, facilityId: "phc-1" },
  },
  {
    username: "lab02",
    role: UserRole.LAB,
    description: "Shalini Mishra · Biochemistry Analyst (District Hosp)",
    user: { id: "lb-02", name: "Shalini Mishra (Biochem)", role: UserRole.LAB, facilityId: "dh-1" },
  },
  {
    username: "lab03",
    role: UserRole.LAB,
    description: "Mohan Lal · Radiographer / X-Ray (Kosi CHC)",
    user: { id: "lb-03", name: "Mohan Lal (Radiology)", role: UserRole.LAB, facilityId: "chc-1" },
  },
  {
    username: "lab04",
    role: UserRole.LAB,
    description: "Priyanka Das · Microbiology Tech (Rampur PHC)",
    user: { id: "lb-04", name: "Priyanka Das", role: UserRole.LAB, facilityId: "phc-1" },
  },
  {
    username: "lab05",
    role: UserRole.LAB,
    description: "Rakesh Pandey · Hematology Specialist (District Hosp)",
    user: { id: "lb-05", name: "Rakesh Pandey (Hematology)", role: UserRole.LAB, facilityId: "dh-1" },
  },

  // 5 Security Staff
  {
    username: "security01",
    role: UserRole.SECURITY,
    description: "Bahadur Singh · Main Gate Security (Rampur PHC)",
    user: { id: "sec-01", name: "Bahadur Singh (Security)", role: UserRole.SECURITY, facilityId: "phc-1" },
  },
  {
    username: "security02",
    role: UserRole.SECURITY,
    description: "Om Prakash · Emergency Ward Gate (District Hosp)",
    user: { id: "sec-02", name: "Om Prakash", role: UserRole.SECURITY, facilityId: "dh-1" },
  },
  {
    username: "security03",
    role: UserRole.SECURITY,
    description: "Rameshwar Das · OPD Flow Marshall (Kosi CHC)",
    user: { id: "sec-03", name: "Rameshwar Das", role: UserRole.SECURITY, facilityId: "chc-1" },
  },
  {
    username: "security04",
    role: UserRole.SECURITY,
    description: "Santosh Yadav · Night Shift Security",
    user: { id: "sec-04", name: "Santosh Yadav", role: UserRole.SECURITY, facilityId: "phc-1" },
  },
  {
    username: "security05",
    role: UserRole.SECURITY,
    description: "Harish Chand · Campus Security Supervisor",
    user: { id: "sec-05", name: "Harish Chand", role: UserRole.SECURITY, facilityId: "dh-1" },
  },

  // 5 Super Admins
  {
    username: "superadmin01",
    role: UserRole.SUPER_ADMIN,
    description: "Dr. Arvind Swaminathan · National Health Mission Dir",
    user: { id: "sa-01", name: "Dr. Arvind Swaminathan (NHM)", role: UserRole.SUPER_ADMIN },
  },
  {
    username: "superadmin02",
    role: UserRole.SUPER_ADMIN,
    description: "Pooja Bhatt · State Digital Health Officer",
    user: { id: "sa-02", name: "Pooja Bhatt (State Admin)", role: UserRole.SUPER_ADMIN },
  },
  {
    username: "superadmin03",
    role: UserRole.SUPER_ADMIN,
    description: "Karan Singhal · Lead Platform Engineer",
    user: { id: "sa-03", name: "Karan Singhal (Tech Lead)", role: UserRole.SUPER_ADMIN },
  },
  {
    username: "superadmin04",
    role: UserRole.SUPER_ADMIN,
    description: "Dr. R. K. Mukherjee · DGHS Health Ministry",
    user: { id: "sa-04", name: "Dr. R. K. Mukherjee", role: UserRole.SUPER_ADMIN },
  },
  {
    username: "superadmin05",
    role: UserRole.SUPER_ADMIN,
    description: "Simran Kaur · National Security & Compliance",
    user: { id: "sa-05", name: "Simran Kaur (Auditor)", role: UserRole.SUPER_ADMIN },
  },
];

import { FacilityType } from "@/dto/constants/FacilityType";

export const initialFacilities: Facility[] = [
  {
    id: "phc-1",
    name: "Rampur Primary Health Centre",
    type: FacilityType.PHC,
    district: "Rampur",
    village: "Rampur",
    state: "Uttar Pradesh",
    address: "Village Rampur, Sector 4, Dist. Rampur - 244901",
    phone: "+91 595 2341001",
    specialties: ["General Medicine", "Pediatrics", "Gynecology", "Emergency Triage"],
    bedCapacity: 12,
    occupiedBeds: 7,
    availableBeds: 5,
    totalBeds: 12,
  },
  {
    id: "chc-1",
    name: "Kosi Community Health Centre",
    type: FacilityType.CHC,
    district: "Kosi",
    village: "Kosi Kalan",
    state: "Uttar Pradesh",
    address: "Main Highway Road, Kosi Kalan - 281403",
    phone: "+91 566 2289004",
    specialties: ["General Medicine", "Surgery", "Pediatrics", "Obstetrics", "Diagnostic Pathology"],
    bedCapacity: 30,
    occupiedBeds: 21,
    availableBeds: 9,
    totalBeds: 30,
  },
  {
    id: "dh-1",
    name: "District Hospital, Kosi",
    type: FacilityType.DISTRICT_HOSPITAL,
    district: "Kosi",
    village: "Kosi",
    state: "Uttar Pradesh",
    address: "Civil Lines, Near Collectorate, Kosi - 281401",
    phone: "+91 566 2200112",
    specialties: ["Cardiology", "Orthopedics", "General Medicine", "Radiology", "ICU", "Blood Bank"],
    bedCapacity: 150,
    occupiedBeds: 118,
    availableBeds: 32,
    totalBeds: 150,
  },
  {
    id: "phc-2",
    name: "Sitapur Primary Health Centre",
    type: FacilityType.PHC,
    district: "Sitapur",
    village: "Sitapur",
    state: "Uttar Pradesh",
    address: "Rural Block Sitapur, Dist. Sitapur - 261001",
    phone: "+91 586 2244009",
    specialties: ["General Medicine", "Maternal Care", "Immunization"],
    bedCapacity: 10,
    occupiedBeds: 4,
    availableBeds: 6,
    totalBeds: 10,
  },
  {
    id: "sub-1",
    name: "Dhanwantri Nagar Sub-Centre",
    type: FacilityType.SUB_CENTRE,
    district: "Rampur",
    village: "Dhanwantri Nagar",
    state: "Uttar Pradesh",
    address: "Dhanwantri Gram Panchayat, Rampur",
    phone: "+91 595 2998811",
    specialties: ["First Aid", "Triage", "ASHA Maternal Care"],
    bedCapacity: 2,
    occupiedBeds: 1,
    availableBeds: 1,
    totalBeds: 2,
  },
];

export const initialPatients: Patient[] = [
  {
    swasthyaId: "SS-IND-00024581",
    name: "Meera Sharma",
    age: 58,
    gender: "Female",
    dob: "1968-04-12",
    village: "Dhanwantri Nagar",
    district: "Rampur",
    state: "Uttar Pradesh",
    bloodGroup: "O+",
    phone: "+91 98765 43210",
    emergencyContact: {
      name: "Suresh Sharma",
      relationship: "Husband",
      phone: "+91 98765 43211",
    },
    riskLevel: RiskLevel.HIGH,
    allergies: ["Penicillin", "Sulfa drugs"],
    registeredAt: "2024-03-12",
    registeredVia: "AYUSHMAN",
    ayushmanCardNo: "PMJAY-UP-9842-1102",
    abhaId: "meera.sharma@abdm",
    homeFacilityId: "phc-1",
    currentVisitId: "vst-101",
  },
  {
    swasthyaId: "SS-IND-00024582",
    name: "Ramesh Patel",
    age: 45,
    gender: "Male",
    dob: "1981-08-20",
    village: "Shivpur",
    district: "Rampur",
    state: "Uttar Pradesh",
    bloodGroup: "B+",
    phone: "+91 98765 43212",
    emergencyContact: {
      name: "Geeta Patel",
      relationship: "Wife",
      phone: "+91 98765 43213",
    },
    riskLevel: RiskLevel.MODERATE,
    allergies: ["Dust"],
    registeredAt: "2024-05-02",
    registeredVia: "ABHA",
    abhaId: "ramesh.patel@abdm",
    homeFacilityId: "phc-1",
    currentVisitId: "vst-102",
  },
  {
    swasthyaId: "SS-IND-00024583",
    name: "Sunita Devi",
    age: 34,
    gender: "Female",
    dob: "1992-01-19",
    village: "Kosi Kalan",
    district: "Kosi",
    state: "Uttar Pradesh",
    bloodGroup: "A+",
    phone: "+91 98765 43214",
    emergencyContact: {
      name: "Manoj Devi",
      relationship: "Brother",
      phone: "+91 98765 43215",
    },
    riskLevel: RiskLevel.MODERATE,
    allergies: ["Latex"],
    registeredAt: "2024-01-19",
    registeredVia: "NORMAL",
    homeFacilityId: "chc-1",
  },
  {
    swasthyaId: "SS-IND-00024584",
    name: "Arjun Singh",
    age: 62,
    gender: "Male",
    dob: "1964-11-05",
    village: "Sitapur Village",
    district: "Sitapur",
    state: "Uttar Pradesh",
    bloodGroup: "AB-",
    phone: "+91 98765 43216",
    emergencyContact: {
      name: "Rajesh Singh",
      relationship: "Son",
      phone: "+91 98765 43217",
    },
    riskLevel: RiskLevel.HIGH,
    allergies: [],
    registeredAt: "2023-11-05",
    registeredVia: "AYUSHMAN",
    ayushmanCardNo: "PMJAY-UP-5510-9923",
    homeFacilityId: "phc-2",
  },
  {
    swasthyaId: "SS-IND-00024585",
    name: "Kavita Joshi",
    age: 28,
    gender: "Female",
    dob: "1998-07-22",
    village: "Mohanpur",
    district: "Rampur",
    state: "Uttar Pradesh",
    bloodGroup: "O-",
    phone: "+91 98765 43218",
    emergencyContact: {
      name: "Devendra Joshi",
      relationship: "Father",
      phone: "+91 98765 43219",
    },
    riskLevel: RiskLevel.LOW,
    allergies: ["Aspirin"],
    registeredAt: "2024-07-22",
    registeredVia: "NORMAL",
    homeFacilityId: "sub-1",
  },
];

export const initialMedicines: Medicine[] = [
  {
    id: "med-1",
    barcode: "890123456701",
    name: "Paracetamol 500mg",
    generic: "Acetaminophen",
    strength: "500mg",
    category: "Analgesic / Antipyretic",
    facilityId: "phc-1",
    stockQty: 1200,
    reorderLevel: 200,
    unit: "tablet",
    mrp: 2.5,
    batches: [
      { batchNo: "PCM-2026-A1", expiryDate: "2027-08-31", stockQty: 750, mrp: 2.5, manufacturer: "Cipla Ltd" },
      { batchNo: "PCM-2026-B2", expiryDate: "2026-12-31", stockQty: 450, mrp: 2.5, manufacturer: "Cipla Ltd" },
    ],
    availability: "IN_STOCK",
  },
  {
    id: "med-2",
    barcode: "890123456702",
    name: "Metformin 500mg",
    generic: "Metformin Hydrochloride",
    strength: "500mg",
    category: "Anti-diabetic",
    facilityId: "phc-1",
    stockQty: 85,
    reorderLevel: 150,
    unit: "tablet",
    mrp: 4.0,
    batches: [
      { batchNo: "MET-2026-X1", expiryDate: "2027-03-31", stockQty: 85, mrp: 4.0, manufacturer: "Sun Pharma" },
    ],
    availability: "LOW_STOCK",
  },
  {
    id: "med-3",
    barcode: "890123456703",
    name: "Amlodipine 5mg",
    generic: "Amlodipine Besylate",
    strength: "5mg",
    category: "Antihypertensive",
    facilityId: "phc-1",
    stockQty: 640,
    reorderLevel: 150,
    unit: "tablet",
    mrp: 3.2,
    batches: [
      { batchNo: "AML-2026-C3", expiryDate: "2028-01-31", stockQty: 640, mrp: 3.2, manufacturer: "Torrent Pharma" },
    ],
    availability: "IN_STOCK",
  },
  {
    id: "med-4",
    barcode: "890123456704",
    name: "ORS Sachet",
    generic: "Oral Rehydration Salts (WHO Formula)",
    strength: "21.8g",
    category: "Rehydration",
    facilityId: "phc-1",
    stockQty: 250,
    reorderLevel: 100,
    unit: "sachet",
    mrp: 6.0,
    batches: [
      { batchNo: "ORS-2026-D4", expiryDate: "2027-10-31", stockQty: 250, mrp: 6.0, manufacturer: "FDC Ltd" },
    ],
    availability: "IN_STOCK",
  },
  {
    id: "med-5",
    barcode: "890123456705",
    name: "Azithromycin 500mg",
    generic: "Azithromycin Dihydrate",
    strength: "500mg",
    category: "Antibiotic",
    facilityId: "phc-1",
    stockQty: 430,
    reorderLevel: 150,
    unit: "tablet",
    mrp: 18.0,
    batches: [
      { batchNo: "AZI-2026-E5", expiryDate: "2027-06-30", stockQty: 430, mrp: 18.0, manufacturer: "Lupin Ltd" },
    ],
    availability: "IN_STOCK",
  },
  {
    id: "med-6",
    barcode: "890123456706",
    name: "Pantoprazole 40mg",
    generic: "Pantoprazole Sodium",
    strength: "40mg",
    category: "Gastrointestinal",
    facilityId: "phc-1",
    stockQty: 520,
    reorderLevel: 150,
    unit: "tablet",
    mrp: 8.5,
    batches: [
      { batchNo: "PAN-2026-F6", expiryDate: "2027-11-30", stockQty: 520, mrp: 8.5, manufacturer: "Alkem Labs" },
    ],
    availability: "IN_STOCK",
  },
  {
    id: "med-7",
    barcode: "890123456707",
    name: "Atorvastatin 20mg",
    generic: "Atorvastatin Calcium",
    strength: "20mg",
    category: "Lipid Lowering",
    facilityId: "phc-1",
    stockQty: 380,
    reorderLevel: 100,
    unit: "tablet",
    mrp: 11.0,
    batches: [
      { batchNo: "ATO-2026-G7", expiryDate: "2027-09-30", stockQty: 380, mrp: 11.0, manufacturer: "Dr. Reddy's" },
    ],
    availability: "IN_STOCK",
  },
];

export const initialVisits: HospitalVisit[] = [
  {
    id: "vst-101",
    visitNumber: "VST-00012984",
    patientId: "SS-IND-00024581",
    patientName: "Meera Sharma",
    patientAge: 58,
    patientGender: "Female",
    facilityId: "phc-1",
    facilityName: "Rampur Primary Health Centre",
    doctorName: "Dr. Anita Rao",
    department: "General Medicine",
    tokenNumber: "A-024",
    status: "IN_CONSULTATION",
    qrToken: "SWASTHYASETU://VISIT/TOKEN_HASH_VST_101",
    reason: "Hypertension review & recurring giddiness",
    symptoms: ["Fatigue", "Dizziness", "Headache"],
    chiefComplaint: "Severe dizziness in morning hours and elevated BP",
    vitals: {
      bloodPressureSys: 156,
      bloodPressureDia: 96,
      heartRate: 88,
      temperature: 36.8,
      glucose: 175,
      spo2: 97,
      weightKg: 64,
      heightCm: 156,
    },
    riskLevel: RiskLevel.HIGH,
    prescriptionsCount: 1,
    testsCount: 2,
    createdAt: "2026-09-13T09:15:00Z",
    checkedInAt: "2026-09-13T09:30:00Z",
  },
  {
    id: "vst-102",
    visitNumber: "VST-00012985",
    patientId: "SS-IND-00024582",
    patientName: "Ramesh Patel",
    patientAge: 45,
    patientGender: "Male",
    facilityId: "phc-1",
    facilityName: "Rampur Primary Health Centre",
    doctorName: "Dr. Anita Rao",
    department: "General Medicine",
    tokenNumber: "A-025",
    status: "CHECKED_IN",
    qrToken: "SWASTHYASETU://VISIT/TOKEN_HASH_VST_102",
    reason: "Chest tightness and follow-up BP check",
    createdAt: "2026-09-13T09:40:00Z",
    checkedInAt: "2026-09-13T09:50:00Z",
  },
  {
    id: "vst-103",
    visitNumber: "VST-00012980",
    patientId: "SS-IND-00024583",
    patientName: "Sunita Devi",
    patientAge: 34,
    patientGender: "Female",
    facilityId: "chc-1",
    facilityName: "Kosi Community Health Centre",
    doctorName: "Dr. Priya Singh",
    department: "Obstetrics",
    tokenNumber: "B-012",
    status: "COMPLETED",
    qrToken: "SWASTHYASETU://VISIT/TOKEN_HASH_VST_103",
    reason: "Antenatal routine screening",
    diagnosis: "Healthy gestation at 24 weeks, mild anemia",
    clinicalNotes: "Prescribed Iron and Calcium supplements; advised dietary leafy greens.",
    createdAt: "2026-09-12T10:00:00Z",
    checkedInAt: "2026-09-12T10:15:00Z",
    consultedAt: "2026-09-12T10:45:00Z",
    completedAt: "2026-09-12T11:30:00Z",
  },
];

export const initialTestOrders: TestOrder[] = [
  {
    id: "TST-0091",
    visitId: "vst-101",
    patientId: "SS-IND-00024581",
    patientName: "Meera Sharma",
    facilityId: "phc-1",
    facilityName: "Rampur Primary Health Centre",
    doctorName: "Dr. Anita Rao",
    testName: "CBC (Complete Blood Count)",
    category: "Hematology",
    department: "Pathology",
    tokenNumber: "LAB-014",
    status: "ORDERED",
    clinicalNotes: "Rule out secondary anemia and check baseline platelets.",
    orderedAt: "2026-09-13T10:05:00Z",
  },
  {
    id: "TST-0092",
    visitId: "vst-101",
    patientId: "SS-IND-00024581",
    patientName: "Meera Sharma",
    facilityId: "phc-1",
    facilityName: "Rampur Primary Health Centre",
    doctorName: "Dr. Anita Rao",
    testName: "Fasting Blood Sugar (FBS)",
    category: "Biochemistry",
    department: "Biochemistry",
    tokenNumber: "LAB-015",
    status: "ORDERED",
    clinicalNotes: "Diabetes control evaluation.",
    orderedAt: "2026-09-13T10:06:00Z",
  },
  {
    id: "TST-0088",
    visitId: "vst-103",
    patientId: "SS-IND-00024583",
    patientName: "Sunita Devi",
    facilityId: "chc-1",
    facilityName: "Kosi Community Health Centre",
    doctorName: "Dr. Priya Singh",
    testName: "Hemoglobin (Hb)",
    category: "Hematology",
    department: "Pathology",
    status: "COMPLETED",
    orderedAt: "2026-09-12T10:20:00Z",
    sampleCollectedAt: "2026-09-12T10:35:00Z",
    completedAt: "2026-09-12T11:00:00Z",
    labTechnician: "Dinesh Kumar",
    summary: "Mild microcytic hypochromic anemia (Hb: 10.4 g/dL).",
    keyValues: [
      { label: "Hemoglobin", value: "10.4", unit: "g/dL", referenceRange: "12.0 - 15.5", flag: "ABNORMAL" },
      { label: "RBC Count", value: "4.1", unit: "mil/uL", referenceRange: "3.8 - 5.2", flag: "NORMAL" },
    ],
  },
];

export const initialPrescriptions: Prescription[] = [
  {
    id: "RX-2026-0812",
    visitId: "vst-101",
    patientId: "SS-IND-00024581",
    patientName: "Meera Sharma",
    doctorName: "Dr. Anita Rao",
    facilityId: "phc-1",
    facilityName: "Rampur Primary Health Centre",
    date: "2026-09-13",
    diagnosis: "Essential Hypertension (Stage 2) & Type 2 Diabetes",
    status: "ISSUED",
    items: [
      {
        id: "rxi-1",
        medicineId: "med-1",
        medicineName: "Paracetamol 500mg",
        genericName: "Acetaminophen",
        strength: "500mg",
        dosage: "1-0-1",
        frequency: "Twice daily after meals",
        duration: "5 days",
        quantity: 10,
        dispensedQty: 0,
        isDispensed: false,
        instructions: "Take SOS for headache or body ache",
      },
      {
        id: "rxi-2",
        medicineId: "med-5",
        medicineName: "Azithromycin 500mg",
        genericName: "Azithromycin",
        strength: "500mg",
        dosage: "1-0-0",
        frequency: "Once daily before lunch",
        duration: "5 days",
        quantity: 5,
        dispensedQty: 0,
        isDispensed: false,
        instructions: "Complete 5-day antibiotic course",
      },
      {
        id: "rxi-3",
        medicineId: "med-6",
        medicineName: "Pantoprazole 40mg",
        genericName: "Pantoprazole",
        strength: "40mg",
        dosage: "1-0-0",
        frequency: "Once daily 30m before breakfast",
        duration: "5 days",
        quantity: 5,
        dispensedQty: 0,
        isDispensed: false,
        instructions: "Antacid coverage",
      },
    ],
    notes: "Review BP and glucose levels in 1 week. Avoid excess dietary sodium.",
  },
];

export const initialTransactions: MedicineTransaction[] = [
  {
    id: "TXN-MED-9940",
    transactionId: "TXN-2026-09-0012",
    visitId: "vst-103",
    prescriptionId: "RX-2026-0799",
    patientId: "SS-IND-00024583",
    patientName: "Sunita Devi",
    doctorName: "Dr. Priya Singh",
    pharmacistId: "ph-01",
    pharmacistName: "Ravi Shastri",
    facilityId: "chc-1",
    facilityName: "Kosi Community Health Centre",
    timestamp: "2026-09-12T11:20:00Z",
    items: [
      {
        medicineId: "med-1",
        medicineName: "Paracetamol 500mg",
        genericName: "Acetaminophen",
        strength: "500mg",
        batchNo: "PCM-2026-A1",
        expiryDate: "2027-08-31",
        quantity: 10,
        unitPrice: 2.5,
        totalPrice: 25.0,
        barcodeScanned: "890123456701",
      },
    ],
    totalAmount: 25.0,
    billId: "BILL-2026-00410",
    status: "COMPLETED",
  },
];

export const initialBills: Bill[] = [
  {
    id: "BILL-2026-00410",
    billNumber: "INV-SS-2026-09-00410",
    visitId: "vst-103",
    patientId: "SS-IND-00024583",
    patientName: "Sunita Devi",
    facilityId: "chc-1",
    facilityName: "Kosi Community Health Centre",
    facilityAddress: "Main Highway Road, Kosi Kalan - 281403",
    prescriptionId: "RX-2026-0799",
    transactionId: "TXN-2026-09-0012",
    date: "2026-09-12",
    pharmacistName: "Ravi Shastri",
    doctorName: "Dr. Priya Singh",
    items: [
      {
        id: "bi-1",
        name: "Paracetamol 500mg (10 tabs)",
        category: "MEDICINE",
        quantity: 10,
        batchNo: "PCM-2026-A1",
        unitPrice: 2.5,
        totalPrice: 25.0,
      },
      {
        id: "bi-2",
        name: "Hemoglobin (Hb) Test",
        category: "DIAGNOSTIC",
        quantity: 1,
        unitPrice: 30.0,
        totalPrice: 30.0,
      },
    ],
    subtotal: 55.0,
    discount: 55.0,
    totalAmount: 0.0,
    paymentMode: "GOVT_FREE_SCHEME",
    status: "PAID",
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    timestamp: "2026-09-13T09:15:00Z",
    actorId: "p-01",
    actorName: "Meera Sharma",
    actorRole: UserRole.PATIENT,
    facilityId: "phc-1",
    action: "APPOINTMENT_BOOKED",
    details: "Booked consultation with Dr. Anita Rao at Rampur PHC",
    targetEntity: "VISIT",
    targetId: "vst-101",
  },
  {
    id: "log-2",
    timestamp: "2026-09-13T09:30:00Z",
    actorId: "hs-01",
    actorName: "Rajesh Tiwari",
    actorRole: UserRole.HOSPITAL_STAFF,
    facilityId: "phc-1",
    action: "PATIENT_CHECKED_IN",
    details: "Scanned patient QR and checked in Meera Sharma; issued OPD Token A-024",
    targetEntity: "VISIT",
    targetId: "vst-101",
  },
  {
    id: "log-3",
    timestamp: "2026-09-13T10:05:00Z",
    actorId: "doc-01",
    actorName: "Dr. Anita Rao",
    actorRole: UserRole.DOCTOR,
    facilityId: "phc-1",
    action: "TESTS_ORDERED",
    details: "Ordered CBC and Fasting Blood Sugar diagnostic tests for Meera Sharma",
    targetEntity: "TEST_ORDER",
    targetId: "TST-0091",
  },
  {
    id: "log-4",
    timestamp: "2026-09-13T10:10:00Z",
    actorId: "doc-01",
    actorName: "Dr. Anita Rao",
    actorRole: UserRole.DOCTOR,
    facilityId: "phc-1",
    action: "PRESCRIPTION_CREATED",
    details: "Prescribed Paracetamol 500mg, Azithromycin 500mg, Pantoprazole 40mg (RX-2026-0812)",
    targetEntity: "PRESCRIPTION",
    targetId: "RX-2026-0812",
  },
];
