export enum UserRole {
  PATIENT = "PATIENT",
  HEALTHCARE_WORKER = "HEALTHCARE_WORKER",
  HOSPITAL_STAFF = "HOSPITAL_STAFF",
  ADMIN = "ADMIN",
  DOCTOR = "DOCTOR",
  PHARMACY = "PHARMACY",
  LAB = "LAB",
  SECURITY = "SECURITY",
  SUPER_ADMIN = "SUPER_ADMIN",
}

